INSERT INTO `npc` (`id`, `name`, `headId`, `bodyId`, `legId`, `menu`) VALUES
(0, 'Kanata', 56, 57, 58, '[[\"Binh khí\"],[\"Gia tộc\",\"Thành lập\",\"Lãnh Địa Gia Tộc\",\"Đổi túi quà\",\"Hướng dẫn\"],[\"Hang động sau trường\",\"Nhận thưởng\",\"Cấp 35\",\"Cấp 45\",\"Cấp 55\",\"Cấp 65\",\"Cấp 75\",\"Cấp 95\",\"Cấp 130\"],[\"Lôi đài\",\"Thách đấu\",\"Xem thi đấu\",\"Kết quả\",\"Ninja tài năng\",\"Xếp hạng tài năng\"],[\"Nói chuyện\"]]'),
(1, 'Furoya', 77, 78, 79, '[[\"Y phục\",\"Nón\",\"Áo\",\"Găng tay\",\"Quần\",\"Giày\"],[\"Nói chuyện\"]]'),
(2, 'Ameji', 47, 48, 49, '[[\"Trang sức\",\"Liên\",\"Nhẫn\",\"Ngọc bội\",\"Phù\"],[\"Nhiệm vụ danh vọng\",\"Nhận\",\"Trả\",\"Huỷ\",\"Nhận Geningan\",\"Hướng dẫn\"],[\"Nói chuyện\"]]'),
(3, 'Kiriko', 74, 75, 76, '[[\"Dược phẩm (Yên)\"],[\"Dược phẩm (Xu)\"],[\"Nói chuyện\"]]'),
(4, 'Tabemono', 50, 51, 52, '[[\"Thức ăn (Yên)\"],[\"Thức ăn (Xu)\"],[\"Nói chuyện\"],[\"Thiên Địa bảng\",\"Đăng ký\",\" Chinh phục\",\"Thiên bảng\",\"Địa bảng\",\"Nhận thưởng\",\"Hướng dẫn\"]]'),
(5, 'Kamakura', 80, 81, 82, '[[\"Mở rương\",\"Rương đồ\",\"Bộ sưu tập\",\"Cải trang\",\"Tháo cải trang\"],[\"Lưu tọa độ\"],[\"Vùng Đất Ma Quỷ\",\"Đi tới\",\"Hướng dẫn\"],[\"Nói chuyện\"]]'),
(6, 'Kenshinto', 68, 69, 70, '[[\"Nâng cấp\",\"Thường\",\"Cẩn thận\",\"Hướng dẫn\"],[\"Luyện đá\",\"Yên\",\"Xu\"],[\"Tách\"],[\"Chuyển hóa\"],[\"Luyện ngọc\"],[\"Khảm\"],[\"Gọt Ngọc\"],[\"Tháo Ngọc\"],[\"Nói chuyện\"]]'),
(7, 'Umayaki', 62, 63, 64, '[[\"Nói chuyện\"],[\"Làng Kojin\"],[\"Làng Sanzu\"],[\"Làng Tone\"],[\"Làng chài\"],[\"Làng Chakumi\"],[\"Làng Echigo\"],[\"Làng Oshin\"]]'),
(8, 'Umayaki', 62, 63, 64, '[[\"Trường Hirosaki\"],[\"Trường Haruna\"],[\"Trường Ookaza\"],[\"Nói chuyện\"]]'),
(9, 'Cô Toyotomi', 44, 45, 46, '[[\"Bảng xếp hạng\",\"Top đại gia\",\"Top cao thủ\",\"Top Gia Tộc\",\"Top hang động\"],[\"Nhập học\",\"Ninja Kiếm\",\"Ninja Phi Tiêu\"],[\"Tẩy điểm\",\"Tiềm năng\",\"Kỹ năng\"],[\"Nói chuyện\"],[\"Giao chiến\",\"Tham gia\",\"Thành tích\",\"Hướng dẫn\"]]'),
(10, 'Thầy Ookamesama', 53, 54, 55, '[[\"Bảng xếp hạng\",\"Top đại gia\",\"Top cao thủ\",\"Top Gia Tộc\",\"Top hang động\"],[\"Nhập học\",\"Ninja Kunai\",\"Ninja Cung\"],[\"Tẩy điểm\",\"Tiềm năng\",\"Kỹ năng\"],[\"Nói chuyện\"],[\"Giao chiến\",\"Tham gia\",\"Thành tích\",\"Hướng dẫn\"]]'),
(11, 'Thầy Kazeto', 65, 66, 67, '[[\"Bảng xếp hạng\",\"Top đại gia\",\"Top cao thủ\",\"Top Gia Tộc\",\"Top hang động\"],[\"Nhập học\",\"Ninja Đao\",\"Ninja Quạt\"],[\"Tẩy điểm\",\"Tiềm năng\",\"Kỹ năng\"],[\"Nói chuyện\"],[\"Giao chiến\",\"Tham gia\",\"Thành tích\",\"Hướng dẫn\"]]'),
(12, 'Tajima', 71, 72, 73, '[[\"Nói chuyện\"],[\"Hủy vật phẩm và nhiệm vụ\"],[\"Thứ thân\"],[\"Chủ thân\"],[\"Nhận quà top event\"],[\"Cài đặt mời\"]]'),
(13, 'Khu vực', 0, 0, 0, '[]'),
(14, 'Hashimoto', 59, 60, 61, '[]'),
(15, 'Fujiwara', 89, 90, 91, '[]'),
(16, 'Nao', 86, 87, 88, '[]'),
(17, 'Jaian', 96, 94, 95, '[]'),
(18, 'Bà Rei', 83, 84, 85, '[[\"Nói chuyện\"]]'),
(19, 'Kirin', 97, 98, 99, '[[\"Nói chuyện\"]]'),
(20, 'Soba', 114, 115, 116, '[[\"Nói chuyện\"]]'),
(21, 'Sunoo', 117, 118, 119, '[[\"Nói chuyện\"]]'),
(22, 'Guriin', 120, 121, 122, '[[\"Nói chuyện\"],[\"Ninja đệ nhất\",\"Tham gia\"],[\"Bảng xếp hạng\",\"Kiếm\",\"Tiêu\",\"Kunai\",\"Cung\",\"Đao\",\"Quạt\"]]'),
(23, 'Matsurugi', 100, 101, 102, '[[\"Nói chuyện\"]]'),
(24, 'Okanechan', 103, 104, 105, '[[\"Nạp tiền\"],[\"Nhận thưởng thăng cấp\",\"Cấp 10\",\"Cấp 20\",\"Cấp 30\",\"Cấp40\",\"Cấp 50\",\"Cấp 70\",\"Cấp 90\",\"Cấp 110\",\"Cấp 130\"],[\"Nói chuyện\"]]'),
(25, 'Rikudou', 106, 107, 108, '[[\"Nói chuyện\"],[\"NV mỗi ngày\",\"Nhận\",\"Hủy\",\"Hoàn thành\",\"Đi làm NV\"],[\"NV Truy bắt Tà Thú\",\"Nhận\",\"Hủy\",\"Hoàn Thành\"],[\"Chiến trường\",\"Bạch Giả\",\"Hắc Giả\",\"Tổng kết\",\"Hướng dẫn\"],[\"Thất thú ải\"]]'),
(26, 'Goosho', 109, 110, 111, '[[\"Cửa hàng\"],[\"Quầy sách\"],[\"Thời trang\"],[\"Gia tộc\"]]'),
(27, 'Trụ cơ quan', 0, 0, 0, '[[\"Cắm chìa khóa\"]]'),
(28, 'Shinwa', 128, 129, 130, '[[\"Gian hàng\",\"Đá\",\"Nón\",\"Vũ khí\",\"Áo\",\"Dây chuyền\",\"Găng tay\",\"Nhẫn\",\"Quần\",\"Ngọc bội\",\"Giày\",\"Bùa\",\"Linh tinh\"],[\"Bán vật phẩm\"],[\"Nhận lại vật phẩm\"]]'),
(29, 'Chị Hằng', 131, 132, 133, '[[\"Làm bánh\",\"Bánh thập cẩm\",\"Bánh dẻo\",\"Bánh đậu xanh\",\"Bánh pía\"],[\"Đóng hộp\",\"Hộp bánh thường\",\"Hộp bánh thượng hạng\"],[\"Hướng dẫn\",\"Cách làm bánh\",\"Tìm Thần Thố\",\"Tìm lồng đèn\"],[\"Nói chuyện\"]]'),
(30, 'Rakkii', 134, 135, 136, '[[\"Lật hình\"],[\"Mã quà tặng\"],[\"Vòng quay vip\",\"Thông tin\",\"Tham gia\",\"Luật chơi\"],[\"Vòng quay thường\",\"Thông tin\",\"Tham gia\",\"Luật chơi\"]]'),
(31, 'Lồng đèn', 0, 0, 0, '[[\"Thắp lồng đèn\"]]'),
(32, 'Kagai', 143, 144, 145, '[[\"Chiến trường kẹo\",\"Tham gia\",\"Hướng dẫn\"],[\"Gia tộc chiến\",\"Thách Đấu\"],[\"Liên Server\",\"Hướng dẫn\"],[\"Đổi điểm hoạt động\",\"Bí kíp 3 ngày\",\"Bí kíp 7 ngày\",\"Bí kíp 15 ngày\"],[\"Tinh luyện\",\"Luyện tinh thạch\",\"Tinh luyện vật phẩm\",\"Dịch chuyển trang bị\",\"Hướng dẫn\"]]'),
(33, 'Tiên nữ', 131, 132, 133, '[[\"Luyện đan cao cấp\"],[\"Luyện đan thường\"],[\"Hướng dẫn\"]]'),
(34, 'Cây thông', 249, 250, 251, '[[\"Nhận quà\"],[\"Trang trí\"],[\"Hướng dẫn\"]]'),
(35, 'Ông già Noel', 168, 169, 170, '[[\"Đổi mặt nạ\"],[\"Hướng dẫn\"]]'),
(36, 'Vua Hùng', 191, 192, 193, '[[\"Đổi coin sang lượng\"],[\"Chuyển sinh\"],[\"Nói chuyện\"]]'),
(37, 'Kanata', 56, 57, 58, '[[\"Rời khỏi nơi này\"],[\"Đặt cược\"],[\"Nói chuyện\"]]'),
(38, 'ADMIN', 159, 197, 198, '[[\"Nhận quà hang động\"],[\"Nhận quà tân thủ\"],[\"Bật/Tắt nhận EXP\"],[\"Tài khoản chính thức\",\"Nhận lại yên\", \"Nhận lại xu\", \"Nhận lại lượng\", \"Nhận lại EXP\"],[\"Reset Phân Thân\"],[\"Hướng dẫn\"]]'),
(39, 'Rikudou', 106, 107, 108, '[[\"Rời khỏi nơi này\"],[\"Thông tin\"]]'),
(40, 'Kagai', 143, 144, 145, '[]'),
(41, 'Đậu Thần Cấp 10', 281, 282, 283, '[[\"Thu Hoạch\"],[\"Hướng dẫn\"]]'),
(42, 'cờ bạc coin', 56, 57, 58, '[[\"Chẵn Lẻ 10tr xu\"],[\"Chẵn Lẻ 50tr xu\"],[\"Chẵn Lẻ 100tr xu\"],[\"Chẵn Lẻ 10k lượng\"],[\"Chẵn Lẻ 50k lượng\"],[\"Chẵn Lẻ 100k lượng\"],[\"Đổi Bí Kíp\",\"Bí kíp kiếm\",\"Bí kíp Tiêu\",\"Bí kíp Đao\",\"Bí kíp Quạt\",\"Bí kíp Kunia\",\"Bí kíp Cung\"],[\"Hướng Dẫn\"]]'),
(43, 'Cây đào', 255, 256, 257, '[[\"Hái lộc\"],[\"Hướng dẫn\"]]'),
(44, '[[\"Nhận quà VIP\",\"VIP 1\",\"VIP 2\",\"VIP 3\",\"VIP 4\",\"VIP 5\",\"VIP 6\",\"VIP 12\",\"VIP 18\"],[\"Báo danh VIP\"],[\"Đổi xu hàng ngày\"],[\"Đặc quyền VIP\",\"Bật tắt exp\",\"Mở rộng 120 ô hành trang\"],[\"Hướng dẫn\"]]'),
(45, 'Mị Nương', 194, 195, 196, '[[\"Chuyển Sinh \"],[\"ĐỔI PHÁI CHỦ THÂN\",\"Kiếm\",\"Tiêu\",\"Kunai\",\"Cung\",\"Đao\",\"Quạt\"],[\"ĐỔI PHÁI PHÂN THÂN\",\"Kiếm\",\"Tiêu\",\"Kunai\",\"Cung\",\"Đao\",\"Quạt\"],[\"tách VK (mcs)\"],[\"xóa all đồ trong rương\"],[\"Hướng Dẫn\"]]'),
(46, 'Mini Game coin', 223, 224, 225, '[[\"Tài Xỉu\",\"Tài\",\"Xỉu\",\"Soi Cầu\"],[\"Chẵn Lẻ\",\"Chẵn\",\"Lẻ\",\"Soi Cầu\"],[\"Xem coin\"],[\"Hướng dẫn\"]]'),
(47, 'ăn mày', 201, 202, 203, '[[\"cho tiền\",\"xin 10k\"]]'),
(48, 'phó bản', 124, 224, 225, '[[\"Phó bản\",\"Cải lão hoàn đồng\",\"Làng Lá\"],[\"cải lão\",\"Cải lão sức mạnh\",\"Cải lão thân pháp\",\"Cải lão thể lực\",\"Cải lão chakra\"]]'),
(49, 'Quy Lão Kame', 278, 279, 280, '[[\"Đổi Xu\"],[\"Đổi Yên\"],[\"Đổi lượng\"]]'),
(50, 'Thiên sứ Whis', 272, 274, 273, '[[\"Nâng cấp Mặt Nạ\"],[\"Nâng cấp Bí Kíp\"],[\"Nâng cấp Yoroi\"],[\"Nâng cấp Pét\"],[\"Nâng cấp Mắt\"],[\"Nâng cấp ntgt\"],[\"Nâng 6 ô hành trang\"]]'),
(51, 'tu luyện', 143, 144, 145, '[[\"Thần men đại hiệp\",\"lv 1\",\"lv 2\",\"lv 3\",\"lv 4\",\"lv 5\",\"lv 6\",\"lv 7\",\"lv 8\",\"lv 9\",\"lv 10\",\"lv 11\",\"lv 12\",\"lv 13\",\"lv 14\",\"lv 15\",\"lv 16\",\"lv 17\",\"xem Thần men hiện tại\",\"Xem exp bia333\",\"Hướng Dẫn\"],[\"đấu khí\",\"đấu khí\",\"đấu giả\",\"đấu sư\",\"đấu linh\",\"đấu vương\",\"đấu hoàng \",\"đấu tông\",\"đấu tôn\",\"đấu đế\",\"xem cấp hiện tại\",\" xem xp hiện tại\",\"hướng dẫn\"]]'),
(52, 'cờ bạc xu', 56, 57, 58, '[[\"Tài Xỉu\",\"Tài\",\"Xỉu\",\"Soi Cầu\"],[\"Chẵn Lẻ\",\"Chẵn\",\"Lẻ\",\"Soi Cầu\"],[\"Hướng dẫn\"]]'),
(53, 'cờ bạc lượng', 56, 57, 58, '[[\"Tài Xỉu\",\"Tài\",\"Xỉu\",\"Soi Cầu\"],[\"Chẵn Lẻ\",\"Chẵn\",\"Lẻ\",\"Soi Cầu\"],[\"Hướng dẫn\"]]'),
(54, 'Thần Mèo Karin', 291, 292, 293, '[[\"Nhận Bí Kíp\"],[\"Hướng Dẫn\"]]'),
(55, 'Bulma', 298, 299, 300, '[[\"Tặng Hoa\"],[\"Nhận Quà\",\"Set Bulma\",\"Set Vegeta Vô Cực\",\"Set Xên\"],[\"Xem Điểm\"],[\"Hướng Dẫn\"]]'),
(56, 'BXH', 131, 132, 133, '[[\"BXH Yên\"],[\"BXH lever\"],[\"BXH gia tộc\"],[\"BXH hang động\"],[\"BXH tiêu lượng\"],[\"BXH chiến lực\"],[\"BXH tiềm năng\"],[\"BXH chuyển sinh\"],[\"BXH nạp\"],[\"BXH câu cá\"],[\"BXH Bợm nhậu\"],[\"BXH Cắn Đan\"],[\"BXH diệt boss ngày\"]]'),
(57, 'MAP UP LƯỢNG', 298, 299, 300, '[[\"MAP UP lượng\",\"Map vip 6\",\"Map vip 12\",\"Map vip 18\"],[\"hướng dẫn\"]]'),
(58, 'Tửu Đại Hiệp', 159, 32, 33, '[[\"Oẳn Tù Tì\",\"Bao\",\"Búa\",\"Kéo\"],[\"Đổi Quà\"],[\"Hướng Dẫn\"]]'),
(59, 'đổi mk khẩu', 159, 197, 198, '[[\"đổi mật khẩu\"]]'),
(60, 'đổi vk vip', 71, 72, 73, '[[\"đổi vk vip\"],[\"đổi vk siêu vip\"]]'),
(61, 'Hồn Cốt', 65, 66, 67, '[[\"Hồn cốt\",\"hồn cốt 1 vạn năm\",\"hồn cốt 2 vạn năm\",\"hồn cốt 3 vạn năm\",\"hồn cốt 4 vạn năm\",\"hồn cốt 5 vạn năm\",\"hồn cốt 6 vạn năm\",\"hồn cốt 7 vạn năm\",\"hồn cốt 8 vạn năm\",\"hồn cốt 9 vạn năm\",\"hồn cốt 10 vạn năm\",\"hồn cốt 100 vạn năm\",\"lv hồn cốt\",\"exp hồn lực\",\"hướng dẫn\"]]'),
(62, 'Tình Fox', 103, 66, 225, '[[\"đoán mò cùng Tình fox\",\"cái này có\",\"cái này có\",\"cái này có\"],[\"Đổi danh thiếp\"],[\"Hướng Dẫn\"]]'),
(63, 'bảo vệ ', 103, 66, 225, '[[\"đổi danh thiếp\",\"danh thiếp cấp 1\",\"danh thiếp cấp 2\",\"danh thiếp cấp 3\",\"danh thiếp cấp 4\",\"danh thiếp cấp 5\",\"danh thiếp cấp 6\",\"hướng dẫn\"]]'),
(64, 'nhận hồn cốt', 103, 66, 225, '[[\"nhận hồn cốt\",\"hồn cốt 1 vạn năm\",\"hồn cốt 7 vạn năm\",\"hồn cốt 100 vạn năm\"]]'),
(65, 'Shop Ma Thần', 341, 339, 340, '[[\"shop đồ 10x\",\"đổi quần gấu bông\",\"đổi áo gấu bông\",\"đổi mặt nạ gấu bông\",\"đổi cây kẹo mật\",\"Hướng dẫn\"]]'),
(66, 'Gấu Ấp Thuê', 337, 336, 335, '[[\"Ấp trứng\",\"ấp trứng hải mã\",\"ấp trứng dị long\",\"ấp trứng khủng long\"],[\"Tiến hóa hải mã\",\"hải mã thiếu niên\",\"hải mã trưởng thành\"],[\"Tiến hóa dị long\",\"dị long thiếu niên\",\"dị long trưởng thành\"],[\"Tiến hóa khủng long\",\"khủng long thiếu niên\",\"khủng long trưởng thành\"],[\"Hướng dẫn\"]]'),
(67, 'Nhục Thân Phái sức mạnh', 343, 344, 345, '[[\"phái kiếm\",\"cấp 1\",\"cấp 2\",\"cấp 3\",\"cấp 4\",\"cấp 5\",\"cấp 6\",\"cấp 7\",\"cấp 8\",\"cấp 9\"],[\"phái kunai\",\"cấp 1\",\"cấp 2\",\"cấp 3\",\"cấp 4\",\"cấp 5\",\"cấp 6\",\"cấp 7\",\"cấp 8\",\"cấp 9\"],[\"phái đao\",\"cấp 1\",\"cấp 2\",\"cấp 3\",\"cấp 4\",\"cấp 5\",\"cấp 6\",\"cấp 7\",\"cấp 8\",\"cấp 9\"],[\"xem lv nhục thân\",\"lv nhục thân\"],[\"xem exp nhục thân\",\"exp nhục thân\"],[\"hướng dẫn\",\"đọc hướng dẫn\"]]'),
(68, 'Nhục Thân Phái nội công', 343, 344, 345, '[[\"phái tiêu\",\"cấp 1\",\"cấp 2\",\"cấp 3\",\"cấp 4\",\"cấp 5\",\"cấp 6\",\"cấp 7\",\"cấp 8\",\"cấp 9\"],[\"phái cung\",\"cấp 1\",\"cấp 2\",\"cấp 3\",\"cấp 4\",\"cấp 5\",\"cấp 6\",\"cấp 7\",\"cấp 8\",\"cấp 9\"],[\"phái quạt\",\"cấp 1\",\"cấp 2\",\"cấp 3\",\"cấp 4\",\"cấp 5\",\"cấp 6\",\"cấp 7\",\"cấp 8\",\"cấp 9\"],[\"xem lv nhục thân\",\"lv nhục thân\"],[\"xem exp nhục thân\",\"exp nhục thân\"],[\"hướng dẫn\",\"đọc hướng dẫn\"]]'),
(69, 'PHÚ HÀO TNK', 347, 348, 349, '[[\"PHÚ HÀO\",\"MỞ PHÚ HÀO\",\"PHÚ HÀO 1\",\"PHÚ HÀO 2\",\"PHÚ HÀO 3\",\"PHÚ HÀO 4\",\"PHÚ HÀO 5\",\"PHÚ HÀO 6\",\"PHÚ HÀO 7\",\"PHÚ HÀO 8\",\"CẤP BẬC PHÚ HÀO \",\"hướng dẫn\"]]'),
(70, 'TẠP HÓA NHÂN PHẨM', 351, 352, 353, '[[\"ĐỔI ĐỒ\",\"MẶT NẠ ZORO\",\"ÁO ZORO\",\"QUẦN ZORO\",\"CHÂN THÂN ZORO\",\"MẶT NẠ TNK\",\"ÁO TNK\",\"QUẦN TNK\",\"CHÂN THÂN TNK\",\"BÁNH BĂNG HỎA\",\"BÁNH PHONG LÔI\",\"HUY CHƯƠNG CÂU CÁ\",\"TÚI XU\",\"TÚI LƯỢNG\",\"hướng dẫn\"]]'),
(71, 'Tài Xỉu 2.0', 343, 344, 345, '[[\"Thông tin\"],[\"Đặt tài\"],[\"Đặt xỉu\"],[\"Soi cầu\"],[\"Hướng dẫn\"]]'),
(72, 'SỨ GIẢ', 59, 60, 61, '[[\"ĐỔI ĐỒ\",\"CÁNH THIÊN THẦN\",\"CÁNH ĐỊA NGỤC\",\"ĐÁ ngũ sắc\",\"đổi tử tinh thạch cao lấy đá ngũ sắc\",\"vk kiếm thần\",\"vk tiêu thần\",\"vk kunai thần\",\"vk cung thần\",\"vk đao thần\",\"vk quạt thần\",\"hướng dẫn\"]]'),
(73, 'sứ giả không gian', 62, 63, 64, '[[\"DỊCH CHUYỂN\",\"hành tinh kamado\"]]'),
(74, 'ước ngọc rồng', 168, 169, 170, '[[\"CẦU ĐƯỢC ƯỚC THẤY\",\"ước được nhiều lượng\",\"ước được nhiều xu\",\"ước đẹp trai nhất server \",\"ước có người yêu\",\"ước được quyền admin\",\"ước full đồ mua\",\"ước 2 tỷ coin\",\"ước Đá ngũ sắc\",\"Hướng dẫn\"]]');
